//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.ChiTietDonMua = new HashSet<ChiTietDonMua>();
        }
    
        public int MaKH { get; set; }
        public string HoTenKH { get; set; }
        public Nullable<int> SDT { get; set; }
        public string GioiTinh { get; set; }
        public string GiaChi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> DiemKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonMua> ChiTietDonMua { get; set; }
        public virtual LoaiKH LoaiKH { get; set; }
    }
}
