//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CNPMNCEntities1 : DbContext
    {
        public CNPMNCEntities1()
            : base("name=CNPMNCEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonMua> ChiTietDonMua { get; set; }
        public virtual DbSet<DonMua> DonMua { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LoaiKH> LoaiKH { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
